### ISSUE TITLE
'NoneType' object has no attribute 'size' when launching game

### ISSUE THREAD

**Issue by JonasGroeger** [stocyr/Deflectouch#7]
Hello everyone.

Im new to Kivy but not python. In my opinion the best way to learn anything is to pick something you like built with it and disassemble it :) So I came to this project.

Unfortunately I cannot start it in the first place.

Here is what I get:

    $ python main.py
    [INFO   ] Kivy v1.6.0
    [INFO   ] [Logger      ] Record log in /home/jonas/.kivy/logs/kivy_13-03-29_7.txt
    [INFO   ] [Factory     ] 137 symbols loaded
    [DEBUG  ] [Cache       ] register <kv.lang> with limit=None, timeout=Nones
    [DEBUG  ] [Cache       ] register <kv.image> with limit=None, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.atlas> with limit=None, timeout=Nones
    [INFO   ] [Image       ] Providers: img_tex, img_dds, img_pygame, img_pil, img_gif 
    [DEBUG  ] [Cache       ] register <kv.texture> with limit=1000, timeout=60s
    [DEBUG  ] [Cache       ] register <kv.shader> with limit=1000, timeout=3600s
    [DEBUG  ] [Audio       ] register SoundGstreamer
    [DEBUG  ] [Audio       ] register SoundPygame
    [INFO   ] [Audio       ] Providers: audio_gstreamer, audio_pygame (audio_sdl ignored)
    [DEBUG  ] [Cache       ] register <kv.loader> with limit=500, timeout=60s
    [INFO   ] [Loader      ] using a thread pool of 2 workers
    [INFO   ] [Text        ] Provider: pygame
    [DEBUG  ] [App         ] Loading configuration <./deflectouch.ini>
    [DEBUG  ] [App         ] Loading kv <./deflectouch.kv>
    [INFO   ] [Window      ] Provider: pygame
    [DEBUG  ] [Window      ] Display driver x11
    [DEBUG  ] [Window      ] Actual window size: 800x600
    [DEBUG  ] [Window      ] Actual color bits r8 g8 b8 a0
    [DEBUG  ] [Window      ] Actual depth bits: 24
    [DEBUG  ] [Window      ] Actual stencil bits: 8
    [DEBUG  ] [Window      ] Actual multisampling samples: 4
    [INFO   ] [GL          ] OpenGL version <3.0 Mesa 9.0.2>
    [INFO   ] [GL          ] OpenGL vendor <Intel Open Source Technology Center>
    [INFO   ] [GL          ] OpenGL renderer <Mesa DRI Intel(R) Ivybridge Mobile >
    [INFO   ] [GL          ] OpenGL parsed version: 3, 0
    [INFO   ] [GL          ] Shading version <1.30>
    [INFO   ] [GL          ] Texture max size <8192>
    [INFO   ] [GL          ] Texture max units <16>
    [DEBUG  ] [Shader      ] Fragment compiled successfully
    [DEBUG  ] [Shader      ] Vertex compiled successfully
    [DEBUG  ] [ImagePygame ] Load </usr/lib/pymodules/python2.7/kivy/data/glsl/default.png>
     Traceback (most recent call last):
       File "/usr/lib/pymodules/python2.7/kivy/modules/__init__.py", line 183, in update
         self.activate_module(name, win)
       File "/usr/lib/pymodules/python2.7/kivy/modules/__init__.py", line 143, in activate_module
         module = self.mods[name]['module']
     KeyError: 'module'
    [WARNING] [WinPygame   ] SDL wrapper failed to import!
    [DEBUG  ] [Window      ] Ignored <sdl> (import error)
    [DEBUG  ] [Window      ] Ignored <x11> (import error)
    [CRITICAL] [Window      ] Unable to find any valuable Window provider at all!

    Deflectouch v1.0  Copyright (C) 2012  Cyril Stoller
    This program comes with ABSOLUTELY NO WARRANTY
    This is free software, and you are welcome to redistribute it
    under certain conditions; see the source code for details.

     Traceback (most recent call last):
       File "main.py", line 542, in <module>
         Deflectouch().run()
       File "/usr/lib/pymodules/python2.7/kivy/app.py", line 527, in run
         root = self.build()
       File "main.py", line 470, in build
         self.deflectouchwidget = DeflectouchWidget(app=self)
       File "/usr/lib/pymodules/python2.7/kivy/uix/widget.py", line 150, in __init__
         Builder.apply(self)
       File "/usr/lib/pymodules/python2.7/kivy/lang.py", line 1247, in apply
         self._apply_rule(widget, rule, rule)
       File "/usr/lib/pymodules/python2.7/kivy/lang.py", line 1338, in _apply_rule
         self.apply(child)
       File "/usr/lib/pymodules/python2.7/kivy/lang.py", line 1247, in apply
         self._apply_rule(widget, rule, rule)
       File "/usr/lib/pymodules/python2.7/kivy/lang.py", line 1361, in _apply_rule
         value, rule, rctx['ids'])
       File "/usr/lib/pymodules/python2.7/kivy/lang.py", line 1063, in create_handler
         raise BuilderException(rule.ctx, rule.line, str(e))
     kivy.lang.BuilderException: Parser: File "./deflectouch.kv", line 35:
     ...
          33:    allow_stretch: True
          34:    keep_ratio: False
     >>   35:    size: win.Window.size
          36:
          37:# Stock Bar description
     ...
     'NoneType' object has no attribute 'size'

Also I am using `Kivy v1.6.0` under `Python 2.7.3` under `Linux Kernel 3.8.4 SMP x86_64`.

I hope somebody can help me out on this one.

**Comment by stocyr** [comment]
The stock bar length issue was solved with commit 933c487dbcf56c197eb897f7a9da827fee508084
